version: '3'
services:
  dashboard:
    restart: always
    build: .
    command: python -u run.py
    ports:
      - '5000:5000'
  fintex_tlg_bot:
    restart: always
    build: ./fintex_tlg_bot
    command: python3 -u ./main.py
    links:
      - database
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: '10'
    depends_on:
      - database
  database:
    restart: always
    ports:
      - '27017:27017'
    image: mongo
    volumes:
      - '/Volumes/FinTEx_Super_Platform/:/data/db/'
mongo-express:
  restart: always
  image: mongo-express
environment:
  - ME_CONFIG_MONGODB_SERVER=database
  - ME_CONFIG_MONGODB_PORT=27017
  - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
  - ME_CONFIG_MONGODB_AUTH_DATABASE=AGF
  - ME_CONFIG_BASICAUTH_USERNAME=admin
  - ME_CONFIG_BASICAUTH_PASSWORD=fintex_unicorn
links:
  - database
logging:
  driver: json-file
  options:
    max-size: 1m
    max-file: '10'
